version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: macmillernz-firefox_firefox_1
      APP_PORT: 3000

  firefox:
    image: lscr.io/linuxserver/firefox:1156.0build1-1xtradeb1.2404.1-ls123@sha256:549e3f7e631169c4763709f1b29c035f561849cd1603f9e47f598b831fc4b9d6
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data:/config
    shm_size: "1gb"
