version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: macmillernz-chromium_chromium_1
      APP_PORT: 3000

  chromium:
    image: lscr.io/linuxserver/chromium:b1ee1dc8-ls55@sha256:cf6200ccdcb224feaf5d3bde4ce45b3783c926a7496c98059cae1e0db78e5b2f
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data:/config
    shm_size: "1gb"
